= OpenShift 4 Advanced Application Deployment ILT Homework Grading

This repository contains the scripts that students can use to validate that their homework assignment will pass.

The automatic grading process requires a private student repository at https://homework-gitea.apps.shared.na.openshift.opentlc.com.

== Student Repository Structure

A skeleton student repository is provided at https://github.com/redhat-gpte-devopsautomation/ocp4_app_deploy_homework_template.

See the homework assignment lab on instructions what to implement. Also see the README files in the skeleton repo on how to build and deploy the applications.

== Grading process

As part of the grading the student's scripts are being executed by a pipeline. If the entire pipeline finishes successfully the homework assignment is graded as *passed*. If the pipeline fails the homework assignmend is graded as *failed*.

Students can verify that the homework assignment will pass by running the pipeline themselves before submitting the assignment.

== How to set up the Jenkins to run the test

. Make sure you are logged in as a `cluster-admin` user (e.g. `system:admin`).
. Create a Jenkins Project (e.g. `gpte-jenkins`) in your cluster.
+
[source,bash]
----
oc new-project gpte-jenkins --description "GPTE Homework Grading Jenkins"
----

. Deploy a persistent Jenkins (the parameters in JENKINS_OPTS define that Jenkins should start Agent Pods immediately every time a build is started rather than waiting for another build to finish).
+
[source,bash]
----
oc new-app jenkins-persistent --param JENKINS_SERVICE_NAME=homework-jenkins --param JNLP_SERVICE_NAME=homework-jenkins-jnlp --param ENABLE_OAUTH=true --param MEMORY_LIMIT=4Gi --param VOLUME_CAPACITY=10Gi --param DISABLE_ADMINISTRATIVE_MONITORS=true --env JENKINS_JAVA_OVERRIDES="-Dhudson.slaves.NodeProvisioner.initialDelay=0 -Dhudson.slaves.NodeProvisioner.MARGIN=50 -Dhudson.slaves.NodeProvisioner.MARGIN0=0.85 -Dorg.jenkinsci.plugins.durabletask.BourneShellScript.HEARTBEAT_CHECK_INTERVAL=300" -n gpte-jenkins
oc set resources dc/homework-jenkins --limits=memory=4Gi,cpu=4 --requests=memory=2Gi,cpu=2 -n gpte-jenkins
----
+
. Create a custom Cluster-Role and grant it to the `jenkins` service account to annotate projects. Also allow the `jenkins` service account to create projects.
+
[source,bash]
----
oc create clusterrole namespace-patcher --verb=patch --resource=namespaces

oc adm policy add-cluster-role-to-user namespace-patcher -z homework-jenkins -n gpte-jenkins
oc adm policy add-cluster-role-to-user self-provisioner -z homework-jenkins -n gpte-jenkins
----

. Once Jenkins is up and running log into Jenkins.
. In Jenkins create a new Item of type *Pipeline*.
. Use the following settings in the Item:
.. Name: Grade Advanced Application Deployment Homework
.. Check the checkbox next to "This build is parametrized"
.. Create seven parameters:
+
[options="header"]
|====
|Parameter|Type|Description
|*GUID*|String|GUID to prefix all projects. Use the GUID provided to you when you requested your homework environment.
|*CREDENTIAL_NAME*|String|Name of the credential in Jenkins holding the student's OpenTLC/Gitea User ID and Gitea Password  (e.g. wkulhane-redhat.com). The User ID is also used to grant admin access for created projects and set the project requester field.
|*REPO*|String|Name of the private repository (do not include the hostname and user of Gitea)
|*CLUSTER*|String|Grading Cluster base URL. E.g. shared.na.openshift.opentlc.com
|*SETUP*|Boolean|Default: true, If *true* will create all necessary projects. If *false* assumes that projects are already there and only pipelines need to be executed.
|*DELETE*|Boolean|Default: true, If *true* will delete all created projects after a successful run.
|*SUBMIT_GRADE*|Boolean|Default: false, If *true* will submit the result of the pipeline run to the LMS.
|====
+
. Use `https://github.com/redhat-gpte-devopsautomation/ocp4_app_deploy_homework_grading` as the Git Repo and `Jenkinsfile` as the Jenkinsfile.

. If this is a shared Jenkins (e.g. on the NA GPTE Cluster) allow students to start builds:
.. Log into Jenkins
.. Navigate to *Manage Jenkins* -> *Configure Global Security*
.. Leave *Matrix based security* and check the checkboxes under *Job* to allow *authenticated users* to *Build* and *Cancel* builds.
.. Also check the checkboxes under *Credentials* to allow *authenticated users* to *Create* credentials.
.. Click *Save*.
. Create the custom agent image that will be used to run the pipeline:
+
[source,sh]
----
oc new-build https://github.com/redhat-gpte-devopsautomation/ocp4_app_deploy_homework_grading.git --strategy=docker --name=jenkins-agent-homework
----

Now you are ready to try the pipeline. Run the pipeline and provide the appropriate parameters for your environment.

The pipeline will:

* Check out your source code repository
* Call your shell scripts to
** Create projects
** Setup Jenkins
** Setup the Development Project
** Setup the Production Project
* Execute the pipeline for your application for the initial (green) deployment.
* Check that the application returns the correct application name
* Execute the pipeline again to execute the blue deployment
* Again check that the application returns the correct application name
* Delete the projects

If the pipeline completes successfully you have passed the homework assignment.
